[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
padding.x = 20
padding.y = 20

startup_mode = "Maximized"
decorations = "None"
opacity = 0.92
blur = true

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font]
size = 13.0

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]
